In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[ 1.0771542 ,  2.12872125, -0.83763942],
       [ 1.10449252,  1.04093048, -0.9514157 ],
       [-0.54719245, -1.42062165,  0.5383416 ],
       [-0.49756219, -0.6127929 , -1.41054955]])

In [1]:
#data_Frame = pd.Series(data) #Bunu etsək xəta verər çünki Series 1 ölçülü dataları tutmaq üçün istifadə edilir

In [9]:
data_frame = pd.DataFrame(data)

In [10]:
data_frame

          0         1         2
0  1.077154  2.128721 -0.837639
1  1.104493  1.040930 -0.951416
2 -0.547192 -1.420622  0.538342
3 -0.497562 -0.612793 -1.410550

In [11]:
type(data_frame)#Bunun typi DataFrame

pandas.core.frame.DataFrame

In [12]:
type(data_frame[0]) #Bunun typıda Series çünki dataframe lərdə Serieslərin birləşməsi nəticəsində yaranır

pandas.core.series.Series

In [13]:
new_dt = pd.DataFrame(data,index=["Nicat","Aygün","Tural","Maqsud"] , columns = ["Salary","Age","Seniority"])

In [14]:
new_dt

          Salary       Age  Seniority
Nicat   1.077154  2.128721  -0.837639
Aygün   1.104493  1.040930  -0.951416
Tural  -0.547192 -1.420622   0.538342
Maqsud -0.497562 -0.612793  -1.410550

In [15]:
new_dt["Age"] #Yalniz yas colonunu al

Nicat     2.128721
Aygün     1.040930
Tural    -1.420622
Maqsud   -0.612793
Name: Age, dtype: float64

In [16]:
new_dt["Salary"] #Yalniz maas colonunu al

Nicat     1.077154
Aygün     1.104493
Tural    -0.547192
Maqsud   -0.497562
Name: Salary, dtype: float64

In [18]:
new_dt[["Age","Salary"]] #Birdən çox colonu gətirmək

             Age    Salary
Nicat   2.128721  1.077154
Aygün   1.040930  1.104493
Tural  -1.420622 -0.547192
Maqsud -0.612793 -0.497562

In [19]:
#-----------Rowa görə axtarış -------  new_dt["Nicat"] xəta verəcək çünki bu sütunlara baxır

In [20]:
new_dt.loc["Nicat"] #Rowa görə axtarış

Salary       1.077154
Age          2.128721
Seniority   -0.837639
Name: Nicat, dtype: float64

In [21]:
#Rowdakilərui indeksə görə gəirmə

In [22]:
new_dt.iloc[0] #0 inci indeksdƏ olan işci

Salary       1.077154
Age          2.128721
Seniority   -0.837639
Name: Nicat, dtype: float64

In [23]:
#Colonlari indeksə görə gətirmə

In [24]:
new_dt.iloc[:,1] #Birinci indeksdəki kolon

Nicat     2.128721
Aygün     1.040930
Tural    -1.420622
Maqsud   -0.612793
Name: Age, dtype: float64

In [25]:
#Dataya əlavə etmələr

In [26]:
new_dt["Extra"] = 10

In [30]:
new_dt

          Salary       Age  Seniority  Extra
Nicat   1.077154  2.128721  -0.837639     10
Aygün   1.104493  1.040930  -0.951416     10
Tural  -0.547192 -1.420622   0.538342     10
Maqsud -0.497562 -0.612793  -1.410550     10

In [36]:
new_dt.drop("Extra",axis=1) #Drop Extra sütünunu silir 
#axis = 0  sətirdəki Extrani sil ,axis = 1 sütüundaki extranı sil-Default olaraq 0 dır "Extra" → silmək istədiyin sütunun adıdır
#axis=1 → pandas-a deyir ki sütunu sil

          Salary       Age  Seniority
Nicat   1.077154  2.128721  -0.837639
Aygün   1.104493  1.040930  -0.951416
Tural  -0.547192 -1.420622   0.538342
Maqsud -0.497562 -0.612793  -1.410550

In [37]:
#Indi bir print(new_dt) desək yenə extra sütunu qalacaq çünki  new_dt.drop("Extra",axis=1)  bu yazılış yeni data 
#qaytarır mövcu olanı dəyişir əgər mövcu datanın dəyişməsini istəyiriksə onda 1 ci yol new_dt = new_dt.drop("Extra",axis=1) yazaq
#2 ci yolda  new_dt.drop("Extra",axis=1,inplace = True) yazaq  inplace = True  dediyimiz an mövcud datanına dəyişir

In [38]:
print(new_dt) # Extrada olacaq

          Salary       Age  Seniority  Extra
Nicat   1.077154  2.128721  -0.837639     10
Aygün   1.104493  1.040930  -0.951416     10
Tural  -0.547192 -1.420622   0.538342     10
Maqsud -0.497562 -0.612793  -1.410550     10

In [39]:
new_dt.drop("Extra",axis=1,inplace = True)

In [40]:
new_dt #extra sutunu silinmis olacaq

          Salary       Age  Seniority
Nicat   1.077154  2.128721  -0.837639
Aygün   1.104493  1.040930  -0.951416
Tural  -0.547192 -1.420622   0.538342
Maqsud -0.497562 -0.612793  -1.410550

In [41]:
#Hüceyrəni almaq

In [43]:
new_dt.loc["Nicat"]["Salary"] #Nicatin maasi 1-ci yol

np.float64(1.0771541952525767)

In [44]:
new_dt.loc["Nicat","Salary"] #Nicatin maasi 2-ci yol

np.float64(1.0771541952525767)

In [45]:
#Hüceyrəni dəyişmək

In [47]:
new_dt.loc["Nicat","Salary"] = 100 #Nicatin maasai 100 edecek

In [48]:
new_dt

            Salary       Age  Seniority
Nicat   100.000000  2.128721  -0.837639
Aygün     1.104493  1.040930  -0.951416
Tural    -0.547192 -1.420622   0.538342
Maqsud   -0.497562 -0.612793  -1.410550

In [49]:
#Filter etmə

In [50]:
new_dt>0

        Salary    Age  Seniority
Nicat     True   True      False
Aygün     True   True      False
Tural    False  False       True
Maqsud   False  False      False

In [51]:
new_dt[new_dt>0]

            Salary       Age  Seniority
Nicat   100.000000  2.128721        NaN
Aygün     1.104493  1.040930        NaN
Tural          NaN       NaN   0.538342
Maqsud         NaN       NaN        NaN

In [53]:
new_dt[new_dt["Salary"]>1]

           Salary       Age  Seniority
Nicat  100.000000  2.128721  -0.837639
Aygün    1.104493  1.040930  -0.951416

In [54]:
new_dt[new_dt["Age"]>1]

           Salary       Age  Seniority
Nicat  100.000000  2.128721  -0.837639
Aygün    1.104493  1.040930  -0.951416

In [55]:
#Indeks dəyişdirmə

In [57]:
new_dt

            Salary       Age  Seniority
Nicat   100.000000  2.128721  -0.837639
Aygün     1.104493  1.040930  -0.951416
Tural    -0.547192 -1.420622   0.538342
Maqsud   -0.497562 -0.612793  -1.410550

In [58]:
new_dt.reset_index() #MÖVCUD indeklər(adlar) üçün yeni bir indeks sütunu yaradır özü isə 0 dan başlayı indeksləyir

    index      Salary       Age  Seniority
0   Nicat  100.000000  2.128721  -0.837639
1   Aygün    1.104493  1.040930  -0.951416
2   Tural   -0.547192 -1.420622   0.538342
3  Maqsud   -0.497562 -0.612793  -1.410550

In [59]:
reset_frame = new_dt.reset_index()

In [60]:
reset_frame.loc["Nicat"] #Bu artiq xeta verecek çünki Nicat artıq indeks deyil nicat olan sətirin indeksi 0 dır

KeyError: 'Nicat'

In [61]:
reset_frame.loc[0]

index           Nicat
Salary          100.0
Age          2.128721
Seniority   -0.837639
Name: 0, dtype: object

In [62]:
#Yeni indeksler yaratmaq

In [63]:
new_indicec = ["Nic","Ayg","Tur","Maq"]

In [64]:
new_dt["NewIndex"] = new_indicec

In [65]:
new_dt

            Salary       Age  Seniority NewIndex
Nicat   100.000000  2.128721  -0.837639      Nic
Aygün     1.104493  1.040930  -0.951416      Ayg
Tural    -0.547192 -1.420622   0.538342      Tur
Maqsud   -0.497562 -0.612793  -1.410550      Maq

In [66]:
#Indi NewIndeksdə olanları indeks halına gətirək

In [67]:
new_dt.set_index("NewIndex",inplace = True)

In [68]:
new_dt

              Salary       Age  Seniority
NewIndex
Nic       100.000000  2.128721  -0.837639
Ayg         1.104493  1.040930  -0.951416
Tur        -0.547192 -1.420622   0.538342
Maq        -0.497562 -0.612793  -1.410550

In [70]:
new_dt.loc["Tur"]

Salary      -0.547192
Age         -1.420622
Seniority    0.538342
Name: Tur, dtype: float64

In [71]:
#multi index

In [72]:
first_index = [ "Simpson",  "Simpson", "Simpson","South Park", "South Park", "South Park"]

In [73]:
inner_index = ["Homer","Bart","Marge","Cartman", "Kenny","Kyle"]

In [74]:
zipped_index = list(zip(first_index,inner_index))

In [75]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [76]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [77]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [79]:
sample_values = np.ones((6,2))

In [82]:
big_df = pd.DataFrame(sample_values,index = zipped_index,columns = ["Age","Salary"])

In [83]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [84]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [87]:
#big_df.loc["Hommer"]#Bu xeta vereck çünki Hommerə çatmaq üçün ilk olaraq simpsonları gətirmək lazımdır

In [88]:
big_df.loc["Simpson"]

       Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [93]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64